version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123

      # HTTPS via ngrok
      - WEBHOOK_URL=https://unnephritic-adalynn-insolvably.ngrok-free.dev
      - N8N_HOST=unnephritic-adalynn-insolvably.ngrok-free.dev
      - N8N_PROTOCOL=https

      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./n8n_data:/home/node/.n8n
